name: Build project

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  testAllModes:
    name: Test in ${{ matrix.testMode }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2020.1.2f1
        testMode:
          - editmode
    steps:
      - uses: webbertakken/unity-test-runner@v1.4
        id: tests
        with:
          projectPath: /Assets/Tests
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}
