# This is a basic workflow to help you get started with Actions

name: MainWorkflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Test Runner
    runs-on: ubuntu-latest
    steps:
    - uses: webbertakken/unity-test-runner@v1.4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        projectPath: https://github.com/MaxPhaneuf/Test-the-tests/tree/master/Assets
        unityVersion: 2020.1.2f1
  
