name: Build project

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  testAllModes:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Unity - Test runner
        uses: webbertakken/unity-test-runner@v2.0-alpha-1
        with:
          unityVersion: 2020.1.2f1
